Rachit Tyagi , 0221csml211 , AIML - C


Import numpy as np # create numpy
array arr = np.array([1, 2, 4, 5, 6]) #flipud method for reversing reverse_
arr = np.flipud(arr)
print(reverse_arr)

In [8]:
import numpy as np
arr = np.array([1, 2, 4, 5, 6])  
reverse_arr = np.flipud(arr)
print(reverse_arr)

[6 5 4 2 1]



Create a class named as Student to store the rollno, name and marks in three subjects. Use List to store the marks. 
a) Write an instance method called compute() to compute total marks and
average marks of a student. 
b) Write a method called display() to display student information

In [9]:
class Student:
    l =[]
    def __init__(self,rollno,name,m1,m2,m3):
        self.rollno = rollno
        self.name = name
        self.l = [m1,m2,m3]
        
    def compute(self):
        self.total_marks = sum(self.l)
        self.avg = self.total_marks/3
    def display(self):
        print('Name :',self.name)
        print('Roll No.:',self.rollno)
        print('Total Marks:',self.total_marks)
        print('Average of Marks',self.avg)
P = Student(1,'Ram',89,90,97)
P.compute()
P.display()

Name : Ram
Roll No.: 1
Total Marks: 276
Average of Marks 92.0



Write a program to demonstrate hybrid inheritance and show MRO for each class

In [10]:
class Vehicle:
  def __init__(self,name):
    print(name,'is a vehicle')

class Run(Vehicle):
  def __init__(self,name):
    print(name,'can run')
    super().__init__(name)
    
class Fly(Vehicle):
  def __init__(self,name):
    print(name,'can fly')
    super().__init__(name)

class Both(Run,Fly):
  def __init__(self,name):
    super().__init__(name)

V = Both('mig')
print(Both.mro())
print(Fly.mro())
print(Run.mro())
print(Vehicle.mro())


mig can run
mig can fly
mig is a vehicle
[<class '__main__.Both'>, <class '__main__.Run'>, <class '__main__.Fly'>, <class '__main__.Vehicle'>, <class 'object'>]
[<class '__main__.Fly'>, <class '__main__.Vehicle'>, <class 'object'>]
[<class '__main__.Run'>, <class '__main__.Vehicle'>, <class 'object'>]
[<class '__main__.Vehicle'>, <class 'object'>]


Write a program to draw colored shapes (line, rectangle, oval) on canvas.

In [11]:
import tkinter as tk
def draw_line():
    canvas.create_line(50,50,200,50,fill = 'red')
def draw_rectangle():
    canvas.create_rectangle(50,100,200,200,fill='blue')
def draw_oval():
    canvas.create_oval(50,250,200,350,fill ='green')
window = tk.Tk()
window.title('drawing shapes')
window.geometry('500x500')

canvas = tk.Canvas(width = 400,height = 400,bg = 'yellowgreen')
canvas.pack()

line_button = tk.Button(text = 'line',command = draw_line)
line_button.pack()

rectangle_button = tk.Button(text = 'rectangle',command = draw_rectangle)
rectangle_button.pack()

oval_button = tk.Button(text = 'oval',command = draw_oval)
oval_button.pack()
window.mainloop()

WAP that extends the class Employee. Derive two classes Manager and Team Leader from Employee class. Display all the details of the employee working under a particular Manager and 


In [12]:

class Employee:
  d = {chr(i):[] for i in range(65,91)}
  def __init__(self, name, emp_id, salary):
        self.name = name
        self.emp_id = emp_id
        self.salary = salary
  def team(self,obj,team):         
    self.d[team].append(obj)
    

         
class Manager(Employee):
    def __init__(self, name, emp_id, salary, team):
        super().__init__(name, emp_id, salary)
        self.designation = 'Manager'
        self.team = team

    def display_team(self):
        print(f"{self.name} \nID: {self.emp_id} \nsalary: {self.salary} \ndesignation: {self.designation} \nteam: {self.team}")
        print()

        print(f"{self.name} is leading the following employees:")
        print()
        for emp in self.d[self.team]:
            print(f"{emp.name} \nID: {emp.emp_id} \nsalary: {emp.salary}")
            print()

class TeamLeader(Employee):
    def __init__(self, name, emp_id, salary, team):
        super().__init__(name, emp_id, salary)
        self.team = team
        self.designation = 'Team Leader'
 
    def display_team(self):
        print(f"{self.name} \nID: {self.emp_id} \nsalary: {self.salary} \ndesignation: {self.designation} \nteam: {self.team}")
        print()

        print(f"{self.name} is leading the following employees:")
        print()
        for emp in self.d[self.team]:
            print(f"{emp.name} \nID: {emp.emp_id} \nsalary: {emp.salary}")
            print()
emp1 = Employee("John", 1, 50000)
emp1.team(emp1,'A')
emp2 = Employee("Jane", 2, 60000)
emp2.team(emp2,'A')
emp3 = Employee("Bob", 3, 55000)
emp3.team(emp3,'B')
emp4 = Employee("Alice", 4, 65000)
emp4.team(emp4,'B')
mgr = Manager("Mike", 5, 75000, 'A')
tl = TeamLeader("Tom", 6, 70000, 'B')

mgr.display_team()
tl.display_team()

Mike 
ID: 5 
salary: 75000 
designation: Manager 
team: A

Mike is leading the following employees:

John 
ID: 1 
salary: 50000

Jane 
ID: 2 
salary: 60000

Tom 
ID: 6 
salary: 70000 
designation: Team Leader 
team: B

Tom is leading the following employees:

Bob 
ID: 3 
salary: 55000

Alice 
ID: 4 
salary: 65000




Write a Program to create a series from a list, numpy array and dict.
list_data = [10, 20, 30, 40, 50]
array_data = ([0.5, 0.8, 1.2, 1.5, 2.0])

In [14]:
import numpy as np
import pandas as pd
l_d = [10,20,30,40,50]
l_s = pd.Series(l_d)
print('Series from list')
print(l_s)
a_d = np.array([0.5,0.8,1.2,1.5,2.0])
a_s = pd.Series(a_d)
print('Series from arrays')
print(a_s)
d_d = {'A':100,'B':200,'C':300,'D':400}
d_s = pd.Series(d_d)
print('Series from dictionary')
print(d_s)


Series from list
0    10
1    20
2    30
3    40
4    50
dtype: int64
Series from arrays
0    0.5
1    0.8
2    1.2
3    1.5
4    2.0
dtype: float64
Series from dictionary
A    100
B    200
C    300
D    400
dtype: int64



What are ways of creating 1D, 2D and 3D arrays in NumPy? Give Examples

in 1- D

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [17]:
import numpy as np

arr = np.arange(1, 6)  # Generates array from 1 to 5
print(arr)


[1 2 3 4 5]


2-D

In [18]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [19]:
import numpy as np

arr = np.zeros((2, 3)) 
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


3-D

In [20]:
import numpy as np

arr = np.ones((2, 3, 4))
print(arr)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]



Write a program that creates an iterator to print squares of numbers

In [15]:
class Square_Iterator:
    def __init__(self,limit):
        self.limit = limit
    def __iter__(self):
        self.a = 1
        return self
    def __next__(self):
        if self.limit>=self.a:
            x = self.a
            self.a+=1
            return x**2
        else:
            raise StopIteration
S = Square_Iterator(10)
for i in S:
    print(i)

1
4
9
16
25
36
49
64
81
100



Create a class Employee that keeps a track of the number of employees in an organization and also stores their name, designation and salary details. 
 a) Write a method called getdata to take input (name, designation,
salary) from user. 
 b) Write a method called average to find average salary of all the
employees in the organization. 
 c) Write a method called display to print all the information of an

In [5]:
class Employee:
  number_of_employees = 0
  total_salary = 0 
  average = 0
  def __init__(self):
    Employee.number_of_employees+=1
  def getdata(self):
    self.name = input("Enter employee name: ")
    self.designation = input("Enter employee designation: ")
    self.salary = int(input("Enter employee salary: "))
    
    Employee.total_salary += self.salary
    Employee.average = Employee.total_salary/Employee.number_of_employees
  def display(self):
    print(self.name,'details :')
    print('Designation :',self.designation)
    print('Salary :',self.salary)
E = Employee()
E.getdata()
E.display()
E.number_of_employees




Remove all rows with NULL values: USING NUMPY AND PANDAS OF YOUR DATASET WHICH YOU HAVE

In [4]:
import pandas as pd
d = pd.read_csv('E:\DAY2\Data\Date1.csv')
print(d)
nd = d.dropna()
print(nd.to_string())

    Duration                Date    Pulse    Maxpulse    Calories
0                 60  '2020/12/01'     110          130     409.1
1                 60  '2020/12/02'     117          145     479.0
2                 60  '2020/12/03'     103          135     340.0
3                 45  '2020/12/04'     109          175     282.4
4                 45  '2020/12/05'     117          148     406.0
5                 60  '2020/12/06'     102          127     300.0
6                 60  '2020/12/07'     110          136     374.0
7                450  '2020/12/08'     104          134     253.3
8                 30  '2020/12/09'     109          133     195.1
9                 60  '2020/12/10'      98          124     269.0
10                60  '2020/12/11'     103          147     329.3
11                60  '2020/12/12'     100          120     250.7
12                60  '2020/12/12'     100          120     250.7
13                60  '2020/12/13'     106          128     345.3
14        


Write a program to count number of missing values in each column.
{'Column1': [1, 2, 3, None, 5],
        'Column2': [6, None, 8, 9, 10],
        'Column3': [11, 12, None, 14, 15]}

In [25]:
import pandas as pd
d = {'column_1': [1,2,3,None,5],'column_2': [6,None,8,9,10],'column_3':[11,12,None,14,15]}
df = pd.DataFrame(d)
print(df.isnull().sum(axis=0))

column_1    1
column_2    1
column_3    1
dtype: int64


# 
Write a program to implement default constructor, parameterized constructor, and destructor.


In [1]:
class Person:
    def __init__(self,name):
        self.name = name
    def __del__(self):
        print("object deleted")
    def display(self):
        print(self.name)
p = Person('Raja')
p.display()
del p

Raja
object deleted


In [2]:
class Person:
    def __init__(self):
        self.name = 'Rachit'
    def display(self):
        print(self.name)
p = Person()
p.display()

Rachit
